language: ruby
cache: bundler

# script: bundle exec rake test TESTOPTS=-v

# http://rubies.travis-ci.org/
# See here for osx_image -> OSX versions: https://docs.travis-ci.com/user/languages/objective-c
matrix:
  include:
    - rvm: 2.1.10
      os: power
    - rvm: 2.2.6
      os: power
    - rvm: 2.3.3
      os: power
    - rvm: 2.4.1
      os: linux
    - rvm: ruby-head
      os: power
  allow_failures:
    - rvm: ruby-head

branches:
  only:
    - master
    - v0.12
    - v0.14

sudo: false
dist: trusty # for TLSv1.2 support

addons:
  apt:
    packages:
      - libgmp3-dev
